name: chisto_networking
description: HTTP networking utilities for Chisto mobile.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  chisto_core:
  connectivity_plus: ^6.1.4
  http: ^1.2.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
