import { ADMIN_PERMISSIONS } from '@/lib/auth/rbac/permissions';
import type { CommandDefinition } from './types';

export const globalCommands: readonly CommandDefinition[] = [
  {
    id: 'open-notifications-panel',
    group: 'actions',
    labelKey: 'openNotificationsPanel',
    descriptionKey: 'openNotificationsPanelDescription',
    messageNamespace: 'commandPalette',
    icon: 'notification-bing',
    keywords: ['alerts', 'bell', 'unread'],
    permission: ADMIN_PERMISSIONS['notifications:read'],
    action: { type: 'open-notifications-panel' },
  },
  {
    id: 'refresh-page',
    group: 'actions',
    labelKey: 'refreshPage',
    descriptionKey: 'refreshPageDescription',
    messageNamespace: 'commandPalette',
    icon: 'refresh',
    keywords: ['reload', 'sync'],
    action: { type: 'refresh-page' },
  },
  {
    id: 'open-profile',
    group: 'actions',
    labelKey: 'openProfileMenu',
    descriptionKey: 'openProfileMenuDescription',
    messageNamespace: 'common',
    icon: 'user',
    keywords: ['account', 'user'],
    action: { type: 'open-profile' },
  },
  {
    id: 'open-preferences',
    group: 'actions',
    labelKey: 'openPreferences',
    descriptionKey: 'openPreferencesDescription',
    messageNamespace: 'common',
    icon: 'setting',
    keywords: ['theme', 'locale', 'motion'],
    href: '/dashboard/settings?section=preferences',
    action: { type: 'navigate', href: '/dashboard/settings?section=preferences' },
  },
  {
    id: 'sign-out',
    group: 'actions',
    labelKey: 'signOutCommand',
    descriptionKey: 'signOutDescription',
    messageNamespace: 'common',
    icon: 'log-out',
    keywords: ['logout', 'exit'],
    action: { type: 'sign-out' },
  },
  {
    id: 'clear-recents',
    group: 'actions',
    labelKey: 'clearRecents',
    descriptionKey: 'clearRecentsDescription',
    messageNamespace: 'commandPalette',
    icon: 'trash',
    keywords: ['history', 'recent'],
    action: { type: 'clear-recents' },
  },
];
