// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'feature_roots_guard_util.dart';

/// Asserts every ARB file under [l10nRoot] exposes the same set of keys.
/// Untranslated keys are a real bug: the runtime [AppLocalizations] getters
/// generated by `flutter gen-l10n` fall back to the default locale silently,
/// so users in MK/SQ can see English copy without anyone noticing.
int runArbKeyParityCheck() {
  final Directory dir = Directory(l10nRoot);
  if (!dir.existsSync()) {
    stderr.writeln('Run from apps/mobile');
    return 2;
  }
  final List<File> files =
      dir
          .listSync(recursive: false)
          .whereType<File>()
          .where((File f) => f.path.endsWith('.arb'))
          .toList()
        ..sort((File a, File b) => a.path.compareTo(b.path));
  if (files.length < 2) {
    stdout.writeln('OK: only ${files.length} ARB file — nothing to compare.');
    return 0;
  }

  final Map<String, Set<String>> keysByFile = <String, Set<String>>{};
  for (final File f in files) {
    final dynamic decoded = jsonDecode(f.readAsStringSync());
    if (decoded is! Map<String, dynamic>) {
      stderr.writeln('ARB ${f.path} is not a JSON object.');
      return 2;
    }
    final Set<String> keys = decoded.keys
        .where((String k) => !k.startsWith('@') && k.isNotEmpty)
        .toSet();
    keysByFile[f.path] = keys;
  }

  final Set<String> union = <String>{
    for (final Set<String> s in keysByFile.values) ...s,
  };

  final List<String> failures = <String>[];
  for (final MapEntry<String, Set<String>> e in keysByFile.entries) {
    final Set<String> missing = union.difference(e.value);
    if (missing.isNotEmpty) {
      failures.add(
        '${e.key} is missing ${missing.length} keys: '
        '${(missing.toList()..sort()).take(10).join(', ')}'
        '${missing.length > 10 ? ', …' : ''}',
      );
    }
  }
  if (failures.isNotEmpty) {
    stderr.writeln('ARB key parity failed:\n${failures.join('\n')}');
    return 1;
  }

  final List<String> placeholderFailures = <String>[];
  final File referenceFile = files.firstWhere(
    (File f) => f.path.endsWith('app_en.arb'),
    orElse: () => files.first,
  );
  final Map<String, dynamic> referenceDecoded =
      jsonDecode(referenceFile.readAsStringSync()) as Map<String, dynamic>;
  final Set<String> metaKeys = referenceDecoded.keys
      .where((String k) => k.startsWith('@') && k.length > 1)
      .toSet();

  for (final String metaKey in metaKeys) {
    final dynamic referenceRaw = referenceDecoded[metaKey];
    if (referenceRaw is! Map<String, dynamic>) {
      continue;
    }
    final Map<String, dynamic> referenceMeta = referenceRaw;
    for (final File f in files) {
      if (f.path == referenceFile.path) {
        continue;
      }
      final Map<String, dynamic> decoded =
          jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
      final dynamic meta = decoded[metaKey];
      if (meta == null) {
        continue;
      }
      if (meta is! Map<String, dynamic>) {
        continue;
      }
      if (!_metadataStructureMatches(referenceMeta, meta)) {
        placeholderFailures.add(
          '${f.path}: $metaKey placeholder/ICU structure differs from reference',
        );
      }
    }
  }

  if (placeholderFailures.isNotEmpty) {
    stderr.writeln(
      'ARB placeholder parity failed:\n${placeholderFailures.join('\n')}',
    );
    return 1;
  }

  stdout.writeln('OK: ${files.length} ARB files share ${union.length} keys.');
  return 0;
}

bool _metadataStructureMatches(
  Map<String, dynamic> a,
  Map<String, dynamic> b,
) {
  final Object? aPlaceholders = a['placeholders'];
  final Object? bPlaceholders = b['placeholders'];
  if (aPlaceholders == null && bPlaceholders == null) {
    return true;
  }
  if (aPlaceholders is! Map || bPlaceholders is! Map) {
    return false;
  }
  if (aPlaceholders.length != bPlaceholders.length) {
    return false;
  }
  for (final MapEntry<dynamic, dynamic> entry in aPlaceholders.entries) {
    final dynamic other = bPlaceholders[entry.key];
    if (other is! Map || entry.value is! Map) {
      return false;
    }
    final Map<dynamic, dynamic> left = entry.value as Map<dynamic, dynamic>;
    final Map<dynamic, dynamic> right = other;
    if (left['type'] != right['type']) {
      return false;
    }
  }
  return true;
}

void main() {
  exit(runArbKeyParityCheck());
}
