// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'feature_roots_guard_util.dart';

/// Asserts every ARB file under [l10nRoot] exposes the same set of keys.
/// Untranslated keys are a real bug: the runtime [AppLocalizations] getters
/// generated by `flutter gen-l10n` fall back to the default locale silently,
/// so users in MK/SQ can see English copy without anyone noticing.
int runArbKeyParityCheck() {
  final Directory dir = Directory(l10nRoot);
  if (!dir.existsSync()) {
    stderr.writeln('Run from apps/mobile');
    return 2;
  }
  final List<File> files =
      dir
          .listSync(recursive: false)
          .whereType<File>()
          .where((File f) => f.path.endsWith('.arb'))
          .toList()
        ..sort((File a, File b) => a.path.compareTo(b.path));
  if (files.length < 2) {
    stdout.writeln('OK: only ${files.length} ARB file — nothing to compare.');
    return 0;
  }

  final Map<String, Set<String>> keysByFile = <String, Set<String>>{};
  for (final File f in files) {
    final dynamic decoded = jsonDecode(f.readAsStringSync());
    if (decoded is! Map<String, dynamic>) {
      stderr.writeln('ARB ${f.path} is not a JSON object.');
      return 2;
    }
    final Set<String> keys = decoded.keys
        .where((String k) => !k.startsWith('@') && k.isNotEmpty)
        .toSet();
    keysByFile[f.path] = keys;
  }

  final Set<String> union = <String>{
    for (final Set<String> s in keysByFile.values) ...s,
  };

  final List<String> failures = <String>[];
  for (final MapEntry<String, Set<String>> e in keysByFile.entries) {
    final Set<String> missing = union.difference(e.value);
    if (missing.isNotEmpty) {
      failures.add(
        '${e.key} is missing ${missing.length} keys: '
        '${(missing.toList()..sort()).take(10).join(', ')}'
        '${missing.length > 10 ? ', …' : ''}',
      );
    }
  }
  if (failures.isNotEmpty) {
    stderr.writeln('ARB key parity failed:\n${failures.join('\n')}');
    return 1;
  }
  stdout.writeln('OK: ${files.length} ARB files share ${union.length} keys.');
  return 0;
}

void main() {
  exit(runArbKeyParityCheck());
}
