import { ApiProperty } from '@nestjs/swagger';
import { IsString, Length, Matches, MaxLength } from 'class-validator';

export class ReportViewerHeartbeatDto {
  @ApiProperty({
    description: 'Stable per-tab session id generated by the admin client',
    example: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  })
  @IsString()
  @Length(8, 64)
  @Matches(/^[A-Za-z0-9_-]+$/, {
    message: 'sessionId must be alphanumeric (UUID or similar)',
  })
  sessionId!: string;

  @ApiProperty({
    description: 'Display name shown to other moderators viewing the same report',
    example: 'Ana Petrova',
  })
  @IsString()
  @MaxLength(120)
  displayName!: string;
}

export class ReportViewerPresenceEntryDto {
  @ApiProperty()
  sessionId!: string;

  @ApiProperty()
  userId!: string;

  @ApiProperty()
  displayName!: string;
}

export class ReportViewerPresenceResponseDto {
  @ApiProperty({ type: [ReportViewerPresenceEntryDto] })
  viewers!: ReportViewerPresenceEntryDto[];
}
