export { AdminShell } from './components/admin-shell';
export { TopBar } from './components/top-bar';
export { TopBarHeader } from './components/top-bar-header';
export { TopBarCommandPalette } from './components/top-bar-command-palette';
export { TopBarNotificationsPanel } from './components/top-bar-notifications-panel';
export { TopBarProfileMenu } from './components/top-bar-profile-menu';
export { DashboardPermissionsProvider } from './components/dashboard-permissions-provider';
export { useTopBarOverlays } from './hooks/use-top-bar-overlays';
export { useTopBarNotifications } from './hooks/use-top-bar-notifications';
export { useBellJiggleOnRealtime } from './hooks/use-bell-jiggle-on-realtime';
export { useWorkspaceRefresh } from './hooks/use-workspace-refresh';
export { useServerSyncedState } from './hooks/use-server-synced-state';
export { useOptimisticMutation } from './hooks/use-optimistic-mutation';
export { useUnsavedChangesGuard } from './hooks/use-unsaved-changes-guard';
export { WorkspaceRefreshOverlay } from './components/workspace-refresh-overlay';
export { DESKTOP_SIDEBAR_COOKIE_KEY, DESKTOP_SIDEBAR_STORAGE_KEY } from './constants';
export { DashboardSegmentError } from './components/dashboard-segment-error';
export { adminNavigation } from './config/navigation';
export type { NavItemKey } from './types';
