import { Controller, Get, Header } from '@nestjs/common';
import { ObservabilityStore } from './observability.store';

@Controller('metrics')
export class MetricsController {
  @Get()
  @Header('Content-Type', 'text/plain; version=0.0.4')
  metrics(): string {
    const s = ObservabilityStore.snapshot();
    return [
      '# HELP api_requests_total Total API requests',
      '# TYPE api_requests_total counter',
      `api_requests_total ${s.requestsTotal}`,
      '# HELP api_requests_failed_total Total 5xx API requests',
      '# TYPE api_requests_failed_total counter',
      `api_requests_failed_total ${s.requestsFailed}`,
      '# HELP api_request_duration_ms_p50 Request duration p50 in milliseconds',
      '# TYPE api_request_duration_ms_p50 gauge',
      `api_request_duration_ms_p50 ${s.p50Ms}`,
      '# HELP api_request_duration_ms_p95 Request duration p95 in milliseconds',
      '# TYPE api_request_duration_ms_p95 gauge',
      `api_request_duration_ms_p95 ${s.p95Ms}`,
      '# HELP api_request_duration_ms_p99 Request duration p99 in milliseconds',
      '# TYPE api_request_duration_ms_p99 gauge',
      `api_request_duration_ms_p99 ${s.p99Ms}`,
      '# HELP feed_requests_total Total feed API responses served',
      '# TYPE feed_requests_total counter',
      `feed_requests_total ${s.feedRequestsTotal}`,
      '# HELP feed_cache_hits_total Feed cache hits',
      '# TYPE feed_cache_hits_total counter',
      `feed_cache_hits_total ${s.feedCacheHits}`,
      '# HELP feed_cache_hit_rate Feed cache hit ratio',
      '# TYPE feed_cache_hit_rate gauge',
      `feed_cache_hit_rate ${s.feedCacheHitRate}`,
      '# HELP feed_request_duration_ms_p95 Feed response duration p95 in milliseconds',
      '# TYPE feed_request_duration_ms_p95 gauge',
      `feed_request_duration_ms_p95 ${s.feedP95Ms}`,
      '# HELP feed_candidate_pool_avg Average candidate pool size before pagination',
      '# TYPE feed_candidate_pool_avg gauge',
      `feed_candidate_pool_avg ${s.feedAvgCandidatePoolSize}`,
      '# HELP feed_request_duration_bucket Feed duration bucket <=100ms',
      '# TYPE feed_request_duration_bucket gauge',
      `feed_request_duration_bucket{le="100"} ${s.feedDurationBuckets.le100}`,
      `feed_request_duration_bucket{le="250"} ${s.feedDurationBuckets.le250}`,
      `feed_request_duration_bucket{le="500"} ${s.feedDurationBuckets.le500}`,
      `feed_request_duration_bucket{le="1000"} ${s.feedDurationBuckets.le1000}`,
      `feed_request_duration_bucket{le="+Inf"} ${
        s.feedDurationBuckets.le1000 + s.feedDurationBuckets.gt1000
      }`,
      '# HELP feed_cache_invalidation_total Feed cache invalidations by reason',
      '# TYPE feed_cache_invalidation_total counter',
      ...Object.entries(s.feedCacheInvalidationCounts).flatMap(([key, value]) => [
        `feed_cache_invalidation_total{reason="${key}"} ${value}`,
      ]),
      '# HELP feed_feedback_total Feed feedback submissions by type',
      '# TYPE feed_feedback_total counter',
      ...Object.entries(s.feedFeedbackCounts).flatMap(([key, value]) => [
        `feed_feedback_total{type="${key}"} ${value}`,
      ]),
      '# HELP feed_reason_code_total Feed ranking reason code occurrences',
      '# TYPE feed_reason_code_total counter',
      ...Object.entries(s.feedReasonCodeCounts).flatMap(([key, value]) => [
        `feed_reason_code_total{reason="${key}"} ${value}`,
      ]),
      '# HELP feed_pagination_continuity_issues_total Feed pages with duplicate IDs',
      '# TYPE feed_pagination_continuity_issues_total counter',
      `feed_pagination_continuity_issues_total ${s.feedPaginationContinuityIssues}`,
      '# HELP push_sends_total Total push notification sends',
      '# TYPE push_sends_total counter',
      `push_sends_total ${s.pushSendsTotal}`,
      '# HELP push_sends_success_total Successful push sends',
      '# TYPE push_sends_success_total counter',
      `push_sends_success_total ${s.pushSendsSuccess}`,
      '# HELP push_sends_failure_total Failed push sends',
      '# TYPE push_sends_failure_total counter',
      `push_sends_failure_total ${s.pushSendsFailure}`,
      '# HELP push_sends_revoked_total Push sends to revoked tokens',
      '# TYPE push_sends_revoked_total counter',
      `push_sends_revoked_total ${s.pushSendsRevoked}`,
      '# HELP push_token_revocations_total Invalid push tokens revoked',
      '# TYPE push_token_revocations_total counter',
      `push_token_revocations_total ${s.pushTokenRevocations}`,
      '# HELP push_queue_retries_total Push delivery queue retries',
      '# TYPE push_queue_retries_total counter',
      `push_queue_retries_total ${s.pushQueueRetries}`,
      '# HELP push_inbox_reads_total Notification inbox read operations',
      '# TYPE push_inbox_reads_total counter',
      `push_inbox_reads_total ${s.pushInboxReads}`,
      '# HELP push_queue_depth Current undelivered push outbox depth',
      '# TYPE push_queue_depth gauge',
      `push_queue_depth ${s.pushQueueDepth}`,
      '# HELP push_active_leases Current push outbox items under lease',
      '# TYPE push_active_leases gauge',
      `push_active_leases ${s.pushActiveLeases}`,
      '# HELP push_dead_letter_total Push outbox rows marked permanently failed',
      '# TYPE push_dead_letter_total gauge',
      `push_dead_letter_total ${s.pushDeadLetterCount}`,
      '# HELP map_requests_total Total map API responses served',
      '# TYPE map_requests_total counter',
      `map_requests_total ${s.mapRequestsTotal}`,
      '# HELP map_cache_hits_total Map cache hits',
      '# TYPE map_cache_hits_total counter',
      `map_cache_hits_total ${s.mapCacheHits}`,
      '# HELP map_cache_hit_rate Map cache hit ratio',
      '# TYPE map_cache_hit_rate gauge',
      `map_cache_hit_rate ${s.mapCacheHitRate}`,
      '# HELP map_fallback_responses_total Map responses served from persisted fallback',
      '# TYPE map_fallback_responses_total counter',
      `map_fallback_responses_total ${s.mapFallbackResponses}`,
      '# HELP map_request_duration_ms_p95 Map response duration p95 in milliseconds',
      '# TYPE map_request_duration_ms_p95 gauge',
      `map_request_duration_ms_p95 ${s.mapP95Ms}`,
      '# HELP map_candidate_pool_avg Average map candidate pool size before filtering',
      '# TYPE map_candidate_pool_avg gauge',
      `map_candidate_pool_avg ${s.mapAvgCandidatePoolSize}`,
      '# HELP map_request_duration_bucket Map duration bucket <=100ms',
      '# TYPE map_request_duration_bucket gauge',
      `map_request_duration_bucket{le="100"} ${s.mapDurationBuckets.le100}`,
      `map_request_duration_bucket{le="250"} ${s.mapDurationBuckets.le250}`,
      `map_request_duration_bucket{le="500"} ${s.mapDurationBuckets.le500}`,
      `map_request_duration_bucket{le="1000"} ${s.mapDurationBuckets.le1000}`,
      `map_request_duration_bucket{le="+Inf"} ${
        s.mapDurationBuckets.le1000 + s.mapDurationBuckets.gt1000
      }`,
      '# HELP map_sse_connections_total Total map SSE subscriptions opened',
      '# TYPE map_sse_connections_total counter',
      `map_sse_connections_total ${s.mapSseConnectionsTotal}`,
      '# HELP map_sse_connections_active Active map SSE subscriptions',
      '# TYPE map_sse_connections_active gauge',
      `map_sse_connections_active ${s.mapSseConnectionsActive}`,
      '# HELP map_sse_reconnect_hints_total Map SSE reconnect hints recorded',
      '# TYPE map_sse_reconnect_hints_total counter',
      `map_sse_reconnect_hints_total ${s.mapSseReconnectHints}`,
      '# HELP map_sse_events_emitted_total Site events emitted over map SSE',
      '# TYPE map_sse_events_emitted_total counter',
      `map_sse_events_emitted_total ${s.mapSseEventsEmitted}`,
      '# HELP map_sse_replay_events_total Replayed map SSE events served from ring buffer',
      '# TYPE map_sse_replay_events_total counter',
      `map_sse_replay_events_total ${s.mapSseReplayEvents}`,
      '',
    ].join('\n');
  }
}
