import { Controller, Get, Header, Headers, UnauthorizedException } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import { ObservabilityStore } from './observability.store';
import { ApiStandardHttpErrorResponses } from '../common/openapi/standard-http-error-responses.decorator';

@ApiTags('metrics')
@ApiStandardHttpErrorResponses()
@Controller('metrics')
export class MetricsController {
  @Get()
  @Header('Content-Type', 'text/plain; version=0.0.4')
  @ApiOperation({ summary: 'Prometheus text exposition (protected outside development when METRICS_BEARER_TOKEN is set)' })
  metrics(@Headers('authorization') authorization?: string): string {
    const token = process.env.METRICS_BEARER_TOKEN?.trim();
    const nodeEnv = (process.env.NODE_ENV ?? 'development').trim().toLowerCase();
    const mustBeProtected = nodeEnv !== 'development' && nodeEnv !== 'test';
    if (mustBeProtected && !token) {
      throw new UnauthorizedException({
        code: 'METRICS_UNAUTHORIZED',
        message: 'Metrics bearer token is required in non-local environments',
      });
    }
    if ((mustBeProtected || !!token) && authorization !== `Bearer ${token}`) {
      throw new UnauthorizedException({
        code: 'METRICS_UNAUTHORIZED',
        message: 'Metrics access denied',
      });
    }
    const s = ObservabilityStore.snapshot();
    return [
      '# HELP api_requests_total Total API requests',
      '# TYPE api_requests_total counter',
      `api_requests_total ${s.requestsTotal}`,
      '# HELP api_requests_failed_total Total 5xx API requests',
      '# TYPE api_requests_failed_total counter',
      `api_requests_failed_total ${s.requestsFailed}`,
      '# HELP api_request_duration_ms_p50 Request duration p50 in milliseconds',
      '# TYPE api_request_duration_ms_p50 gauge',
      `api_request_duration_ms_p50 ${s.p50Ms}`,
      '# HELP api_request_duration_ms_p95 Request duration p95 in milliseconds',
      '# TYPE api_request_duration_ms_p95 gauge',
      `api_request_duration_ms_p95 ${s.p95Ms}`,
      '# HELP api_request_duration_ms_p99 Request duration p99 in milliseconds',
      '# TYPE api_request_duration_ms_p99 gauge',
      `api_request_duration_ms_p99 ${s.p99Ms}`,
      '# HELP feed_requests_total Total feed API responses served',
      '# TYPE feed_requests_total counter',
      `feed_requests_total ${s.feedRequestsTotal}`,
      '# HELP feed_cache_hits_total Feed cache hits',
      '# TYPE feed_cache_hits_total counter',
      `feed_cache_hits_total ${s.feedCacheHits}`,
      '# HELP feed_cache_hit_rate Feed cache hit ratio',
      '# TYPE feed_cache_hit_rate gauge',
      `feed_cache_hit_rate ${s.feedCacheHitRate}`,
      '# HELP feed_request_duration_ms_p95 Feed response duration p95 in milliseconds',
      '# TYPE feed_request_duration_ms_p95 gauge',
      `feed_request_duration_ms_p95 ${s.feedP95Ms}`,
      '# HELP feed_candidate_pool_avg Average candidate pool size before pagination',
      '# TYPE feed_candidate_pool_avg gauge',
      `feed_candidate_pool_avg ${s.feedAvgCandidatePoolSize}`,
      '# HELP feed_request_duration_bucket Feed duration bucket <=100ms',
      '# TYPE feed_request_duration_bucket gauge',
      `feed_request_duration_bucket{le="100"} ${s.feedDurationBuckets.le100}`,
      `feed_request_duration_bucket{le="250"} ${s.feedDurationBuckets.le250}`,
      `feed_request_duration_bucket{le="500"} ${s.feedDurationBuckets.le500}`,
      `feed_request_duration_bucket{le="1000"} ${s.feedDurationBuckets.le1000}`,
      `feed_request_duration_bucket{le="+Inf"} ${
        s.feedDurationBuckets.le1000 + s.feedDurationBuckets.gt1000
      }`,
      '# HELP feed_cache_invalidation_total Feed cache invalidations by reason',
      '# TYPE feed_cache_invalidation_total counter',
      ...Object.entries(s.feedCacheInvalidationCounts).flatMap(([key, value]) => [
        `feed_cache_invalidation_total{reason="${key}"} ${value}`,
      ]),
      '# HELP feed_feedback_total Feed feedback submissions by type',
      '# TYPE feed_feedback_total counter',
      ...Object.entries(s.feedFeedbackCounts).flatMap(([key, value]) => [
        `feed_feedback_total{type="${key}"} ${value}`,
      ]),
      '# HELP feed_reason_code_total Feed ranking reason code occurrences',
      '# TYPE feed_reason_code_total counter',
      ...Object.entries(s.feedReasonCodeCounts).flatMap(([key, value]) => [
        `feed_reason_code_total{reason="${key}"} ${value}`,
      ]),
      '# HELP feed_pagination_continuity_issues_total Feed pages with duplicate IDs',
      '# TYPE feed_pagination_continuity_issues_total counter',
      `feed_pagination_continuity_issues_total ${s.feedPaginationContinuityIssues}`,
      '# HELP feed_v2_requests_total Feed v2 rerank requests',
      '# TYPE feed_v2_requests_total counter',
      `feed_v2_requests_total ${s.feedV2Requests}`,
      '# HELP feed_v2_fallbacks_total Feed v2 rerank fallbacks to v1',
      '# TYPE feed_v2_fallbacks_total counter',
      `feed_v2_fallbacks_total ${s.feedV2Fallbacks}`,
      '# HELP feed_v2_shadow_comparisons_total Feed v2 shadow comparisons',
      '# TYPE feed_v2_shadow_comparisons_total counter',
      `feed_v2_shadow_comparisons_total ${s.feedV2ShadowComparisons}`,
      '# HELP feed_v2_shadow_top10_overlap_avg Feed v2 shadow top-10 overlap average',
      '# TYPE feed_v2_shadow_top10_overlap_avg gauge',
      `feed_v2_shadow_top10_overlap_avg ${s.feedV2ShadowTop10OverlapAvg}`,
      '# HELP feed_v2_shadow_avg_abs_delta Feed v2 shadow average absolute score delta',
      '# TYPE feed_v2_shadow_avg_abs_delta gauge',
      `feed_v2_shadow_avg_abs_delta ${s.feedV2ShadowAvgAbsDelta}`,
      '# HELP feed_v2_model_info Feed v2 model version info',
      '# TYPE feed_v2_model_info gauge',
      `feed_v2_model_info{version="${s.feedV2ModelVersion}"} 1`,
      '# HELP feed_v2_ranker_mode_info Feed v2 active ranker mode',
      '# TYPE feed_v2_ranker_mode_info gauge',
      `feed_v2_ranker_mode_info{mode="${s.feedV2RankerMode}"} 1`,
      '# HELP feed_v2_stage_p95_ms Feed v2 stage p95 latency in milliseconds',
      '# TYPE feed_v2_stage_p95_ms gauge',
      ...Object.entries(s.feedV2StageP95Ms).flatMap(([stage, value]) => [
        `feed_v2_stage_p95_ms{stage="${stage}"} ${value}`,
      ]),
      '# HELP push_sends_total Total push notification sends',
      '# TYPE push_sends_total counter',
      `push_sends_total ${s.pushSendsTotal}`,
      '# HELP push_sends_success_total Successful push sends',
      '# TYPE push_sends_success_total counter',
      `push_sends_success_total ${s.pushSendsSuccess}`,
      '# HELP push_sends_failure_total Failed push sends',
      '# TYPE push_sends_failure_total counter',
      `push_sends_failure_total ${s.pushSendsFailure}`,
      '# HELP push_sends_revoked_total Push sends to revoked tokens',
      '# TYPE push_sends_revoked_total counter',
      `push_sends_revoked_total ${s.pushSendsRevoked}`,
      '# HELP push_token_revocations_total Invalid push tokens revoked',
      '# TYPE push_token_revocations_total counter',
      `push_token_revocations_total ${s.pushTokenRevocations}`,
      '# HELP push_queue_retries_total Push delivery queue retries',
      '# TYPE push_queue_retries_total counter',
      `push_queue_retries_total ${s.pushQueueRetries}`,
      '# HELP push_inbox_reads_total Notification inbox read operations',
      '# TYPE push_inbox_reads_total counter',
      `push_inbox_reads_total ${s.pushInboxReads}`,
      '# HELP push_queue_depth Current undelivered push outbox depth',
      '# TYPE push_queue_depth gauge',
      `push_queue_depth ${s.pushQueueDepth}`,
      '# HELP push_active_leases Current push outbox items under lease',
      '# TYPE push_active_leases gauge',
      `push_active_leases ${s.pushActiveLeases}`,
      '# HELP push_dead_letter_total Push outbox rows marked permanently failed',
      '# TYPE push_dead_letter_total gauge',
      `push_dead_letter_total ${s.pushDeadLetterCount}`,
      '# HELP map_requests_total Total map API responses served',
      '# TYPE map_requests_total counter',
      `map_requests_total ${s.mapRequestsTotal}`,
      '# HELP map_cache_hits_total Map cache hits',
      '# TYPE map_cache_hits_total counter',
      `map_cache_hits_total ${s.mapCacheHits}`,
      '# HELP map_cache_hit_rate Map cache hit ratio',
      '# TYPE map_cache_hit_rate gauge',
      `map_cache_hit_rate ${s.mapCacheHitRate}`,
      '# HELP map_cache_entries Current in-memory map cache entries',
      '# TYPE map_cache_entries gauge',
      `map_cache_entries ${s.mapCacheEntries}`,
      '# HELP map_fallback_responses_total Map responses served from persisted fallback',
      '# TYPE map_fallback_responses_total counter',
      `map_fallback_responses_total ${s.mapFallbackResponses}`,
      '# HELP map_request_duration_ms_p95 Map response duration p95 in milliseconds',
      '# TYPE map_request_duration_ms_p95 gauge',
      `map_request_duration_ms_p95 ${s.mapP95Ms}`,
      '# HELP map_candidate_pool_avg Average map candidate pool size before filtering',
      '# TYPE map_candidate_pool_avg gauge',
      `map_candidate_pool_avg ${s.mapAvgCandidatePoolSize}`,
      '# HELP map_request_duration_bucket Map duration bucket <=100ms',
      '# TYPE map_request_duration_bucket gauge',
      `map_request_duration_bucket{le="100"} ${s.mapDurationBuckets.le100}`,
      `map_request_duration_bucket{le="250"} ${s.mapDurationBuckets.le250}`,
      `map_request_duration_bucket{le="500"} ${s.mapDurationBuckets.le500}`,
      `map_request_duration_bucket{le="1000"} ${s.mapDurationBuckets.le1000}`,
      `map_request_duration_bucket{le="+Inf"} ${
        s.mapDurationBuckets.le1000 + s.mapDurationBuckets.gt1000
      }`,
      '# HELP map_sse_connections_total Total map SSE subscriptions opened',
      '# TYPE map_sse_connections_total counter',
      `map_sse_connections_total ${s.mapSseConnectionsTotal}`,
      '# HELP map_sse_connections_active Active map SSE subscriptions',
      '# TYPE map_sse_connections_active gauge',
      `map_sse_connections_active ${s.mapSseConnectionsActive}`,
      '# HELP map_sse_reconnect_hints_total Map SSE reconnect hints recorded',
      '# TYPE map_sse_reconnect_hints_total counter',
      `map_sse_reconnect_hints_total ${s.mapSseReconnectHints}`,
      '# HELP map_sse_events_emitted_total Site events emitted over map SSE',
      '# TYPE map_sse_events_emitted_total counter',
      `map_sse_events_emitted_total ${s.mapSseEventsEmitted}`,
      '# HELP map_sse_replay_events_total Replayed map SSE events served from ring buffer',
      '# TYPE map_sse_replay_events_total counter',
      `map_sse_replay_events_total ${s.mapSseReplayEvents}`,
      '# HELP map_outbox_dispatched_total Map outbox events successfully dispatched',
      '# TYPE map_outbox_dispatched_total counter',
      `map_outbox_dispatched_total ${s.mapOutboxDispatched}`,
      '# HELP map_outbox_failed_total Map outbox dispatch failures',
      '# TYPE map_outbox_failed_total counter',
      `map_outbox_failed_total ${s.mapOutboxFailed}`,
      '# HELP map_outbox_lag_ms Current lag between event occurrence and outbox dispatch',
      '# TYPE map_outbox_lag_ms gauge',
      `map_outbox_lag_ms ${s.mapOutboxLagMs}`,

      '# HELP map_projection_rows_total Total rows in map projection table (latest sample)',
      '# TYPE map_projection_rows_total gauge',
      `map_projection_rows_total ${s.mapProjectionRowsTotal}`,
      '# HELP map_projection_hot_rows Rows in map projection flagged hot',
      '# TYPE map_projection_hot_rows gauge',
      `map_projection_hot_rows ${s.mapProjectionHotRows}`,
      '# HELP map_projection_staleness_seconds Age in seconds of oldest hot projection row',
      '# TYPE map_projection_staleness_seconds gauge',
      `map_projection_staleness_seconds ${s.mapProjectionStalenessSeconds}`,
      '# HELP map_cold_sites_archived_total Number of rows touched by hotness lifecycle refresh',
      '# TYPE map_cold_sites_archived_total counter',
      `map_cold_sites_archived_total ${s.mapColdSitesArchivedTotal}`,
      '# HELP map_outbox_rows_purged_total Outbox rows purged by TTL cleanup',
      '# TYPE map_outbox_rows_purged_total counter',
      `map_outbox_rows_purged_total ${s.mapOutboxRowsPurgedTotal}`,
      '# HELP map_zoom_tier_requests_total Map requests by zoom tier',
      '# TYPE map_zoom_tier_requests_total counter',
      ...Object.entries(s.mapZoomTierRequests).flatMap(([tier, value]) => [
        `map_zoom_tier_requests_total{tier="${tier}"} ${value}`,
      ]),
      '# HELP map_query_row_count_avg Average row count in map responses',
      '# TYPE map_query_row_count_avg gauge',
      `map_query_row_count_avg ${s.mapAvgQueryRowCount}`,
      '# HELP map_requests_by_mode_zoom_total Map requests by mode and zoom bucket',
      '# TYPE map_requests_by_mode_zoom_total counter',
      ...Object.entries(s.mapRequestsByModeZoom).flatMap(([key, value]) => [
        `map_requests_by_mode_zoom_total{slice="${key}"} ${value}`,
      ]),
      '# HELP map_cache_hits_by_mode_zoom_total Map cache hits by mode and zoom bucket',
      '# TYPE map_cache_hits_by_mode_zoom_total counter',
      ...Object.entries(s.mapCacheHitsByModeZoom).flatMap(([key, value]) => [
        `map_cache_hits_by_mode_zoom_total{slice="${key}"} ${value}`,
      ]),
      '# HELP map_mode_zoom_latency_ms_p95 Map latency p95 by mode and zoom bucket (ms)',
      '# TYPE map_mode_zoom_latency_ms_p95 gauge',
      ...Object.entries(s.mapModeZoomLatencyP95Ms).flatMap(([key, value]) => [
        `map_mode_zoom_latency_ms_p95{slice="${key}"} ${value}`,
      ]),
      '# HELP reports_submit_success_total Successful citizen report submissions',
      '# TYPE reports_submit_success_total counter',
      `reports_submit_success_total ${s.reportsSubmitSuccess}`,
      '# HELP reports_submit_points_awarded_total Legacy: sum of XP once granted on submit (deprecated path)',
      '# TYPE reports_submit_points_awarded_total counter',
      `reports_submit_points_awarded_total ${s.reportsSubmitPointsAwardedTotal}`,
      '# HELP report_approval_points_awarded_total Sum of XP granted when reports are approved',
      '# TYPE report_approval_points_awarded_total counter',
      `report_approval_points_awarded_total ${s.reportApprovalPointsAwardedTotal}`,
      '# HELP report_approval_points_capped_total Report approvals where daily cap reduced the award',
      '# TYPE report_approval_points_capped_total counter',
      `report_approval_points_capped_total ${s.reportApprovalPointsCappedTotal}`,
      '# HELP report_approval_points_revoked_total Points clawed back on APPROVED→DELETED',
      '# TYPE report_approval_points_revoked_total counter',
      `report_approval_points_revoked_total ${s.reportApprovalPointsRevokedTotal}`,
      '# HELP reports_submit_error_total Failed citizen report submissions',
      '# TYPE reports_submit_error_total counter',
      `reports_submit_error_total ${s.reportsSubmitError}`,
      '# HELP reports_upload_success_total Successful report media uploads',
      '# TYPE reports_upload_success_total counter',
      `reports_upload_success_total ${s.reportsUploadSuccess}`,
      '# HELP reports_upload_error_total Failed report media uploads',
      '# TYPE reports_upload_error_total counter',
      `reports_upload_error_total ${s.reportsUploadError}`,
      '# HELP reports_signed_url_issued_total Report media presigned URLs issued (S3)',
      '# TYPE reports_signed_url_issued_total counter',
      `reports_signed_url_issued_total ${s.reportsSignedUrlIssued}`,
      '# HELP reports_signed_url_cache_hit_total Report media presigned URL cache hits',
      '# TYPE reports_signed_url_cache_hit_total counter',
      `reports_signed_url_cache_hit_total ${s.reportsSignedUrlCacheHit}`,
      '# HELP reports_signed_url_error_total Report media presign failures',
      '# TYPE reports_signed_url_error_total counter',
      `reports_signed_url_error_total ${s.reportsSignedUrlError}`,
      '# HELP reports_submit_duration_ms_p95 Report submit path p95 latency (ms)',
      '# TYPE reports_submit_duration_ms_p95 gauge',
      `reports_submit_duration_ms_p95 ${s.reportsSubmitP95Ms}`,
      '# HELP reports_signed_url_latency_ms_p95 Presign latency p95 (ms)',
      '# TYPE reports_signed_url_latency_ms_p95 gauge',
      `reports_signed_url_latency_ms_p95 ${s.reportsSignedUrlLatencyP95Ms}`,
      '',
    ].join('\n');
  }
}
